### ISSUE TITLE
Loading images for a user-provided route

### ISSUE THREAD

**Issue by emichael** [bafolts/google-streetview-images#4]
I've been looking for something to view routes from runs and bike rides with street view, and I came across this project. I'm a little reticent to submit an API key to the website, but it looks like http://www.brianfolts.com/driver/ claims to supports that feature? Is this something you've implemented and could add to this repo?

Thanks!

**Comment by bafolts** [comment]
That website is out of sync with this repository. As google continues to restrict the usage of the streetview API it is more difficult to maintain that website. If you self host the HTML page [here](https://github.com/bafolts/google-streetview-images/blob/master/index.html#L5) you can provide the API key. I would try to use this and we can improve it here if needed.

**Comment by emichael** [comment]
Ah, I see. FWIW, I found this other project after finding yours. It seems to do the job pretty well.

https://github.com/pelmers/streetwarp-cli/
